Fix/month calendar min max prop
Groww-OSS/webster pull request #492
Opened 2024-09-03 11:12 UTC by harshpathakzz

## What does this PR do?

Added min max optional prop in MonthCalendar component

## What packages have been affected by this PR?
ui-toolkit

## Types of changes

What types of changes does your code introduce to this project?

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)

- [ ] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Package version increase in any of the packages?
ui-toolkit -> `0.6.5`

## Checklist before merging

_Put an `x` in the boxes that apply_

- [x] These changes have been thoroughly tested.

- [ ] Changes need to be immediately published on npm.

2024-09-03 11:29 UTC, shubhamgavali1998 commented on packages/ui-toolkit/src/components/molecules/Calendar/MonthCalendar/index.tsx
> +  compareMonth = (date1: Date, date2: Date): number => {
use proper naming conventions instead of date1 and date2

2024-09-04 06:37 UTC, saloni-groww commented on packages/ui-toolkit/src/components/molecules/Calendar/MonthCalendar/index.tsx
> +                })
Can add `cur-po` conditionally when `!this.isNextYearDisabled()`.
Create a constant and then do the conditional check.

2024-09-04 06:37 UTC, saloni-groww commented on packages/ui-toolkit/src/components/molecules/Calendar/MonthCalendar/index.tsx
> +                  'contentSecondary cur-no': this.isPreviousYearDisabled()
Can add `cur-po` conditionally when `!this.isPreviousYearDisabled()`.
Create a constant and then do the conditional check.

2024-09-04 06:37 UTC, saloni-groww commented on packages/ui-toolkit/src/components/molecules/Calendar/MonthCalendar/index.tsx
> +    if (this.isPreviousYearDisabled()) {
Can we create a constant for the result of `this.isPreviousYearDisabled()` and use that instead of invoking the function in the conditions?

2024-09-04 06:37 UTC, saloni-groww commented on packages/ui-toolkit/src/components/molecules/Calendar/MonthCalendar/index.tsx
> +    if (this.isNextYearDisabled()) {
Same as above.

2024-09-04 06:37 UTC, saloni-groww commented on packages/ui-toolkit/src/components/molecules/Calendar/MonthCalendar/index.tsx
> +    const yearDiff = dateOne.getFullYear() - dateTwo.getFullYear();
Can check `dateOne` and `dateTwo` presence here only.
```
if(!dateOne || !dateTwo){
return;
}
```

2024-09-04 06:37 UTC, saloni-groww commented on packages/ui-toolkit/src/components/molecules/Calendar/MonthCalendar/index.tsx
> +    if (minMonth && this.compareMonth(minMonth, currentDate)) {
Can combine both the conditions.
```
if(this.compareMonth(minMonth, currentDate) || this.compareMonth(currentDate, maxMonth)){
return true;
}
```

2024-09-05 08:19 UTC, saloni-groww requested changes

2024-09-05 08:19 UTC, saloni-groww commented on packages/ui-toolkit/src/components/molecules/Calendar/MonthCalendar/index.tsx
> +                cn({ 'valign-wrapper cur-po': !isPreviousYearDisabled }, {
`valign-wrapper` would be a default class. Pls remove it from conditional rendering.

2024-09-05 08:19 UTC, saloni-groww commented on packages/ui-toolkit/src/components/molecules/Calendar/MonthCalendar/index.tsx
> +                cn({ 'valign-wrapper cur-po': !isNextYearDisabled }, {
`valign-wrapper` would be a default class. Pls remove it from conditional rendering.

2024-09-05 09:04 UTC, saloni-groww approved these changes

2024-09-05 09:04 UTC, saloni-groww commented on packages/ui-toolkit/package.json
> +  "version": "0.6.5",
Change version to `0.6.6` since `0.6.5` is already published.

2024-09-05 11:45 UTC, shubhamgavali1998 approved these changes

2024-09-06 08:01 UTC, merged