Feat/input field v2
Groww-OSS/webster pull request #543
Opened 2024-10-09 06:18 UTC by harshpathakzz

## What does this PR do?
Added new forminput , dataRowInput and inputStepper component

## What packages have been affected by this PR?

## Types of changes

What types of changes does your code introduce to this project?

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)

- [x] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Package version increase in any of the packages?

## Checklist before merging

_Put an `x` in the boxes that apply_

- [ ] These changes have been thoroughly tested.

- [ ] Changes need to be immediately published on npm.

2025-01-29 12:37 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/DataRowInput/DataRowInput.tsx
> +    onKeyDown && onKeyDown(e);
Can check `onKeyDown` is a type function or not.

2025-01-29 12:38 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/FreeFormInput/FreeFormInput.tsx
> +    if (onKeyDown) onKeyDown(e);
Same as above

2025-01-29 12:39 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/FreeFormInput/FreeFormInput.tsx
> +                    <PrefixIcon size={20}/>
Please add a comment why are we hardcoding size --> `20`

2025-01-29 12:41 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/FreeFormInput/styles/index.css
> +  font-size: 16px;
Please use fontUtil

2025-01-29 12:42 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/IconButtonV2/IconButtonV2.tsx
> +            size={size === 'small' ? 16 : size === 'large' ? 24 : 20}
Please create a function for size declaration.

2025-01-29 12:43 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/IconButtonV2/IconButtonV2.tsx
> +          <Icon size={size === 'small' ? 16 : size === 'large' ? 24 : 20} />
Same as above.

2025-01-29 12:43 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/IconButtonV2/styles/index.css
> +button{
why are we targetting `button` tag here ?

2025-01-29 12:44 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/InputStepper/InputStepper.tsx
> +    if (e.key === 'Enter' && onEnterPress) {
Please check type for `onEnterPress`.

2025-01-29 12:49 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/InputStepper/InputStepper.tsx
> +import './styles/index.css';
Fix Import.

2025-01-29 12:57 UTC, AkshayNaikGroww requested changes

2025-01-29 12:57 UTC, AkshayNaikGroww commented on packages/ui-toolkit/src/components/atoms/DataRowInput/styles/index.css
> +  padding: 0;
Check if needed

2025-01-29 12:57 UTC, AkshayNaikGroww commented on packages/ui-toolkit/src/components/atoms/FreeFormInput/FreeFormInput.tsx
> +              : variant === 'number'
Check if this block is needed
```              : variant === 'number'
                ? 'number'
                : 'text'```

2025-01-29 12:57 UTC, AkshayNaikGroww commented on packages/ui-toolkit/src/components/atoms/TempIconButtonV2/TempIconButtonV2.tsx
> +  | 'contentSecondary'
Can use ContentMintTokens

2025-01-29 12:57 UTC, AkshayNaikGroww commented on packages/ui-toolkit/src/components/atoms/TempIconButtonV2/styles/index.css
> +  padding: 0;
check this

2025-01-29 12:58 UTC, saloni-groww commented on packages/ui-toolkit/stories/FreeFormInput.stories.tsx
> +  // error: { hasError: false, message: '' },
Please remove the comment.

2025-01-29 13:00 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/InputStepper/InputStepper.tsx
> +    if (onKeyDown) {
Same as above/

2025-01-29 13:04 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/FreeFormInput/FreeFormInput.tsx
> +  error = { hasError: false, message: '' },
Flattem the `error` prop.

2025-01-29 13:04 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/FreeFormInput/FreeFormInput.tsx
> +import './styles/index.css';
Fix import.

2025-01-29 13:05 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/DataRowInput/DataRowInput.tsx
> +import './styles/index.css';
Fix import

2025-01-29 13:06 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/FreeFormInput/FreeFormInput.tsx
> +import { ReactIconComponentType } from '@groww-tech/icon-store/types.d';
Shouldn't it be '@groww-tech/icon-store/types.d.ts' ?

2025-01-29 13:06 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/InputStepper/InputStepper.tsx
> +import { ReactIconComponentType } from '@groww-tech/icon-store/types.d';
Shouldn't it be '@groww-tech/icon-store/types.d.ts' ?

2025-01-29 13:06 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/InputStepper/styles/index.css
> +  position: relative;
please use `pos-rel` utils.

2025-01-29 13:07 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/InputStepper/styles/index.css
> +  width: 100%;
please use `width100`

2025-01-29 13:07 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/InputStepper/styles/index.css
> +  font-size: 16px;
Please use `font` utils.

2025-01-29 13:08 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/InputStepper/styles/index.css
> +  display: flex;
Please use `utils` for this.

2025-01-29 13:08 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/InputStepper/styles/index.css
> +  width: 100%;
Please use utils.

2025-01-29 13:08 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/InputStepper/styles/index.css
> +.inputStepper-inputClearIcon {
Please use utils class.

2025-01-29 13:09 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/FreeFormInput/styles/index.css
> +  display: flex;
Please use utils class.

2025-02-23 20:27 UTC, harshpathakzz commented on packages/ui-toolkit/src/components/atoms/FreeFormInput/FreeFormInput.tsx
> +              : variant === 'number'
Yes we need to apply type for input block

2025-02-24 02:34 UTC, harshpathakzz commented on packages/ui-toolkit/src/components/atoms/FreeFormInput/FreeFormInput.tsx
> +import './styles/index.css';
What is wrong with this import

2025-02-24 02:53 UTC, harshpathakzz commented on packages/ui-toolkit/src/components/atoms/InputStepper/InputStepper.tsx
> +    if (onKeyDown) {
TypeScript ensures that if onKeyDown is provided, it will always be a function with the correct signature.

2025-03-10 13:20 UTC, saloni-groww commented on packages/ui-toolkit/src/components/atoms/DataRowInput/DataRowInput.tsx
> +import type { ReactIconComponentType } from '@groww-tech/icon-store';
fix import.

2025-03-13 12:46 UTC, saloni-groww approved these changes

2025-03-13 13:05 UTC, merged