Migration/UI toolkit semantic tokens v 0.7.9 alpha2
Groww-OSS/webster pull request #578
Opened 2024-11-29 13:06 UTC by harshpathakzz

## What does this PR do?
Migrates primitive tokens to semantic tokens 

## What packages have been affected by this PR?
`ui-toolkit`

## Types of changes

What types of changes does your code introduce to this project?

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)

- [x] New feature (non-breaking change which adds functionality)

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Package version increase in any of the packages?
0.7.9-alpha

## Checklist before merging

_Put an `x` in the boxes that apply_

- [ ] These changes have been thoroughly tested.

- [ ] Changes need to be immediately published on npm.

2024-11-29 13:30 UTC, shubhamgavali1998 commented on packages/ui-toolkit/src/components/atoms/Popover/Popover.tsx
> +        className="pop12Wrapper"
revert these spaces

2024-12-01 10:17 UTC, AkshayNaikGroww requested changes

2024-12-03 12:39 UTC, AkshayNaikGroww requested changes

2024-12-03 12:39 UTC, AkshayNaikGroww commented on packages/ui-toolkit/src/components/atoms/Popover/Popover.tsx
> +          <div className={`pop12Popover contentPrimary borderPrimary borderPrimary backgroundPrimary ${popoverWrapperClass} ${direction || POPOVER_POSITIONS.TOP}`}>
borderPrimary applied twice

2024-12-03 12:39 UTC, AkshayNaikGroww commented on packages/ui-toolkit/src/components/atoms/Tabs/Tabs.tsx
> +      const prevActiveElement = document?.getElementsByClassName('tabs8TextActive contentAccent contentAccent') as HTMLCollectionOf<HTMLElement>;
still present

2024-12-03 12:39 UTC, AkshayNaikGroww commented on packages/ui-toolkit/src/components/atoms/Toastify/toastify.css
>  .sb10ToastifyInfo {
Replace with util class

2024-12-03 13:05 UTC, AkshayNaikGroww approved these changes

2024-12-03 13:08 UTC, merged